- name: app-setup
  include_role:
    name: command
    tasks_from: app-setup

- name: maven-setup
  include_role:
    name: command
    tasks_from: maven-setup
    
- name: systemd-setup
  include_role:
    name: command
    tasks_from: systemd

# - name: connect to mysql using app user
#   community.mysql.mysql_info:
#     login_user: shipping
#     login_password: RoboShop@1
#     login_host: mysql.dontgiveup.space
#     login_db: cities

- name: import data
  tags:
  - import
  community.mysql.mysql_db:
    name: all
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: restart shipping
  ansible.builtin.service:
    state: restarted
    name: shipping